name: pipe
channels:
- conda-forge
- anaconda
- defaults
dependencies:
- dbus=1.13.18
- expat=2.2.10
- pyqt=5.9.2
- qt=5.9.7
- sip=4.19.8
- argon2-cffi=20.1.0
- async_generator=1.10
- attrs=20.3.0
- bleach=3.3.0
- cffi=1.14.5
- defusedxml=0.6.0
- entrypoints=0.3
- importlib-metadata=3.7.0
- importlib_metadata=3.7.0
- ipyfilechooser=0.4.2
- ipywidgets=7.6.3
- jsonschema=3.2.0
- jupyterlab_pygments=0.1.2
- jupyterlab_widgets=1.0.0
- mistune=0.8.4
- nbclient=0.5.3
- nbconvert=6.0.7
- nbformat=5.1.2
- nest-asyncio=1.4.3
- notebook=6.2.0
- packaging=20.9
- pandoc=2.11.4
- pandocfilters=1.4.2
- prometheus_client=0.9.0
- pycparser=2.20
- pyrsistent=0.17.3
- python_abi=3.7
- send2trash=1.5.0
- terminado=0.9.2
- testpath=0.4.4
- typing_extensions=3.7.4.3
- webencodings=0.5.1
- widgetsnbextension=3.5.1
- zipp=3.4.0
- appnope=0.1.2
- backcall=0.2.0
- blas=1.0
- blosc=1.21.0
- brotli=1.0.9
- brunsli=0.1
- bzip2=1.0.8
- ca-certificates=2021.1.19
- cairo=1.14.12
- certifi=2020.12.5
- charls=2.1.0
- cloudpickle=1.6.0
- cycler=0.10.0
- cytoolz=0.11.0
- dask-core=2021.2.0
- decorator=4.4.2
- ffmpeg=4.0
- fontconfig=2.13.1
- freetype=2.10.4
- gettext=0.19.8.1
- giflib=5.1.4
- glib=2.67.4
- graphite2=1.3.14
- harfbuzz=1.8.8
- hdf5=1.10.2
- icu=58.2
- imagecodecs=2021.1.11
- imageio=2.9.0
- intel-openmp=2020.2
- ipykernel=5.3.4
- ipython=7.20.0
- ipython_genutils=0.2.0
- jasper=2.0.14
- jedi=0.17.2
- jinja2=2.11.3
- joblib=1.0.1
- jpeg=9b
- jupyter_client=6.1.7
- jupyter_core=4.7.1
- jxrlib=1.1
- kiwisolver=1.3.1
- lcms2=2.11
- lerc=2.2.1
- libaec=1.0.4
- libcxx=10.0.0
- libdeflate=1.7
- libedit=3.1.20191231
- libffi=3.3
- libgfortran=3.0.1
- libiconv=1.16
- libllvm10=10.0.1
- libopencv=3.4.2
- libopus=1.3.1
- libpng=1.6.37
- libsodium=1.0.18
- libtiff=4.1.0
- libvpx=1.7.0
- libwebp=1.0.1
- libxml2=2.9.10
- libzopfli=1.0.3
- llvm-openmp=10.0.0
- llvmlite=0.34.0
- lz4-c=1.9.3
- markupsafe=1.1.1
- matplotlib=3.3.4
- matplotlib-base=3.3.4
- mkl=2019.4
- mkl-service=2.3.0
- mkl_fft=1.2.1
- mkl_random=1.1.1
- ncurses=6.2
- networkx=2.5
- numba=0.51.2
- numpy=1.19.2
- numpy-base=1.19.2
- olefile=0.46
- opencv=3.4.2
- openjpeg=2.3.0
- openssl=1.1.1j
- pandas=1.2.2
- parso=0.7.0
- pcre=8.44
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=8.1.0
- pims=0.5
- pip=21.0.1
- pixman=0.40.0
- prompt-toolkit=3.0.8
- ptyprocess=0.7.0
- py-opencv=3.4.2
- pygments=2.8.0
- pyparsing=2.4.7
- python=3.7.9
- python-dateutil=2.8.1
- pytz=2021.1
- pywavelets=1.1.1
- pyyaml=5.4.1
- pyzmq=20.0.0
- readline=8.1
- scikit-image=0.17.2
- scikit-learn=0.23.2
- scipy=1.6.1
- seaborn=0.11.1
- setuptools=52.0.0
- six=1.15.0
- slicerator=1.0.0
- snappy=1.1.8
- sqlite=3.33.0
- threadpoolctl=2.1.0
- tifffile=2021.1.14
- tk=8.6.10
- toolz=0.11.1
- tornado=6.1
- traitlets=5.0.5
- wcwidth=0.2.5
- wheel=0.36.2
- xz=5.2.5
- yaml=0.2.5
- zeromq=4.3.3
- zfp=0.5.5
- zlib=1.2.11
- zstd=1.4.5

